{******************************************************************}
{ The contents of this file are used with permission, subject to   }
{ the Mozilla Public License Version 1.1 (the "License"); you may  }
{ not use this file except in compliance with the License. You may }
{ obtain a copy of the License at                                  }
{ http://www.mozilla.org/MPL/MPL-1.1.html                          }
{                                                                  }
{ Software distributed under the License is distributed on an      }
{ "AS IS" basis, WITHOUT WARRANTY OF ANY KIND, either express or   }
{ implied. See the License for the specific language governing     }
{ rights and limitations under the License.                        }
{                                                                  }
{******************************************************************}

//  Marathon Include File

{$IFDEF Ver150}       // Delphi 7
  {$DEFINE DELPHI6+}
  {$DEFINE DELPHI7+}
  {$DEFINE DELPHI5+}
{$ENDIF}
{$IFDEF Ver140}       // Delphi 6
  {$DEFINE DELPHI6+}
  {$DEFINE DELPHI5+}
{$ENDIF}
{$IFDEF Ver130}       // Delphi 5
  {$DEFINE DELPHI5+}
{$ENDIF}

